---
title: "zip_to_LD_v2.Rmd"
author: "Janet Young"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(tidyverse)
library(kableExtra)
library(sf) # for functions like st_join
library(tmap) # for plotting maps
## so we don't have to download big data multiple times
options(tigris_use_cache = TRUE)

load("zip_to_districts_Robjects/zipCodes_by_stateLD_intersect_plain.rda")
load("zip_to_districts_Robjects/WA_state_stateLegDists.rda")
load("zip_to_districts_Robjects/WA_state_zipCodes.rda")
```

make a map of LD1, showing all zip codes that touch it.

```{r LD1 map}

ld1 <- WA_state_stateLegDists %>% 
    filter(NAMELSAD=="State Senate District 1")

ld1_zips <- zipCodes_by_stateLD_intersect_plain %>% 
    # xx congressional_district will be renamed
    filter(congressional_district=="State Senate District 1") %>% 
    arrange(zip_code)

#xxx maybe we filter zips that aren't in WA WA_state_zipCodes
all_zip_maps <- WA_state_zipCodes %>% 
    filter(ZCTA5CE20 >= 98000) %>% 
    filter(ZCTA5CE20 <= 99404)

ld1_zip_maps <- all_zip_maps %>% 
    filter(ZCTA5CE20 %in% ld1_zips$zip_code)
```

Functionalize ^
```{r}
library(glue)

map_ld_zips <- function(district_number) |>
  
  
  
WA_state_stateLegDists |>
  nest(data = -NAMELSAD)

ld1 <- WA_state_stateLegDists %>% 
    filter(NAMELSAD=="State Senate District 1")

ld1_zips <- zipCodes_by_stateLD_intersect_plain %>% 
    # xx congressional_district will be renamed
    filter(congressional_district=="State Senate District 1") %>% 
    arrange(zip_code)

#xxx maybe we filter zips that aren't in WA WA_state_zipCodes
all_zip_maps <- WA_state_zipCodes %>% 
    filter(ZCTA5CE20 >= 98000) %>% 
    filter(ZCTA5CE20 <= 99404)

ld1_zip_maps <- all_zip_maps %>% 
    filter(ZCTA5CE20 %in% ld1_zips$zip_code)
```

```{r}
## shade the ld
# thicker 
# labels on zip codes
# title = LD name


tm_shape(ld1_zip_maps) +
    tm_borders(col = "blue") +
    tm_fill(col="ZCTA5CE20", alpha=0.5,legend.show=FALSE) +
    tm_text("ZCTA5CE20", size=0.5) +
    tm_shape( ld1 ) +  
    tm_fill(col="pink", alpha=0.25) +
    tm_borders(col = "red", lty=2, lwd=2) # +
    #tm_format("ld1_zip_maps",title="LD1")
    

```